# Generated by Django 6.0.3 on 2026-09-01 20:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('display_name', models.CharField(max_length=200)),
                ('marketplace_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHostingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=16)),
                ('requested_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'verbose_name': 'company hosting access',
                'verbose_name_plural': 'company hosting access',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_version', models.CharField(max_length=64)),
                ('shellui_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploading', 'Uploading'), ('ready', 'Ready'), ('active', 'Active'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16)),
                ('pinned', models.BooleanField(default=False)),
                ('storage_prefix', models.CharField(max_length=512)),
                ('deployed_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('artifact_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='hosting.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shellui_min', models.CharField(max_length=64)),
                ('shellui_max', models.CharField(blank=True, default='', max_length=64)),
                ('recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='hosting.app')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='hosting.deployment')),
            ],
            options={
                'ordering': ['-recommended', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='app',
            name='current_deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hosting.deployment'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['app', 'status'], name='hosting_dep_app_id_6b08fc_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['app', 'created_at'], name='hosting_dep_app_id_bb4314_idx'),
        ),
        migrations.AddIndex(
            model_name='appcompatibility',
            index=models.Index(fields=['app', 'recommended'], name='hosting_app_app_id_092c83_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['company_id', 'slug'], name='hosting_app_company_faa8ff_idx'),
        ),
    ]
