# Generated by Django 6.0.3 on 2026-09-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_remove_app_marketplace_visible'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='app',
            new_name='hosting_app_company_aebbdd_idx',
            old_name='hosting_app_company_name_idx',
        ),
    ]
